export const NAV_LOGIN = "NAV_LOGIN";
export const NAV_LOGOUT = "NAV_LOGOUT";
export const NAV_BACK = "NAV_BACK";
export const NAV_HOME = "NAV_HOME";
export const DRAWER_CHANGE_ITEM = "DRAWER_CHANGE_ITEM";
export const NAV_INIT = "NAV_INIT";
export const GO_FORWARD = "GO_FORWARD";

// Auth
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAILURE = "LOGIN_REQUEST_FAILURE";
export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_REQUEST_SUCCESS = "PROFILE_REQUEST_SUCCESS";
export const PROFILE_REQUEST_FAILURE = "PROFILE_REQUEST_FAILURE";

export const READ_AUTH = "READ_AUTH";
export const READ_AUTH_SUCCESS = "READ_AUTH_SUCCESS";
export const WRITE_AUTH = "WRITE_AUTH";
export const DELETE_DATA_SESSION = "DELETE_DATA_SESSION";

// Players
export const PLAYERS_REQUEST = "PLAYERS";
export const PLAYERS_REQUEST_SUCCESS = "PLAYERS_SUCCESS";
export const PLAYERS_REQUEST_FAILURE = "PLAYERS_FAILURE";
export const PLAYER_DETAIL_SELECT = "PLAYER_DETAIL_SELECT";
export const PLAYER_DETAIL_REQUEST = "PLAYER_DETAIL_REQUEST";
export const PLAYER_DETAIL_REQUEST_SUCCESS = "PLAYER_DETAIL_REQUEST_SUCCESS";
export const PLAYER_DETAIL_REQUEST_FAILURE = "PLAYER_DETAIL_REQUEST_FAILURE";
export const PLAYER_DETAIL_GAMES_REQUEST = "PLAYER_DETAIL_GAMES_REQUEST";
export const PLAYER_DETAIL_GAMES_REQUEST_SUCCESS =
  "PLAYER_DETAIL_GAMES_REQUEST_SUCCESS";
export const PLAYER_DETAIL_GAMES_REQUEST_FAILURE =
  "PLAYER_DETAIL_GAMES_REQUEST_FAILURE";

// Games
export const GAMES_REQUEST = "GAMES";
export const GAMES_REQUEST_SUCCESS = "GAMES_SUCCESS";
export const GAMES_REQUEST_FAILURE = "GAMES_FAILURE";
export const GAME_CREATION_REQUEST = "GAME_CREATION_REQUEST";
export const GAME_CREATION_REQUEST_SUCCESS = "GAME_CREATION_REQUEST_SUCCESS";
export const GAME_CREATION_REQUEST_FAILURE = "GAME_CREATION_REQUEST_FAILURE";
export const GAME_DETAIL_REQUEST = "GAME_DETAIL_REQUEST";
export const GAME_DETAIL_REQUEST_SUCCESS = "GAME_DETAIL_REQUEST_SUCCESS";
export const GAME_DETAIL_REQUEST_FAILURE = "GAME_DETAIL_REQUEST_FAILURE";
export const GAME_DETAIL_SELECT = "GAME_DETAIL_SELECT";
